import { useContext } from 'react';
import Head from 'next/head';
import style from '../styles/Home.module.css'; 
import { motion } from 'framer-motion'; 
import { Box, Flex, Avatar, Text } from '@chakra-ui/react';
import { ThemeContext } from '../lib/context';
import images from '../lib/images';

export default function Home() {
  const { darkMode } = useContext(ThemeContext);
/*   const [width, setWidth] = useState(0);

  const carousel = useRef();
  const inn = useRef();
  const bar = useRef();
   */
  /* useEffect(() => {
    setWidth(carousel.current.scrollWidth - carousel.current.offsetWidth)
  }, []); */

  return (
    <Box className={darkMode ? [style.wrapper_dark, style.wrapper].join(" ") 
         : [style.wrapper_light, style.wrapper].join(" ")}   
    >   
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={darkMode ?  [style.main_dark, style.main].join(" ") 
            :  [style.main_light, style.main].join(" ")}
            width={['100vw', '100vw','75vw', '75vw']}
            display='flex'
            justifyContent='center'
            alignItems='center'
      >
         {/*  <motion.div ref={carousel} className={style.carousel}>
            <motion.div ref={inn} className={style.inner_carousel}
                        drag="x" 
                        dragConstraints={{right: 0, left: -width}}
                        whileTap={{cursor: "grabbing"}}
            >
              {images.map(image => {
                  return (
                      <motion.div  key={image.src} className={style.item}>
                          <img src={image.src} alt={image.src} />
                      </motion.div>
                  );
              })}
            </motion.div>
          </motion.div> */}
        <Flex 
            direction='column' 
            align='center' 
            justify='space-around'
            gap='1rem'
            p='20px'
            height={['70%','100%','100%','100%']}
        >
              <Avatar name='Carlos Quintero' size={['lg','xl','2xl','2xl']}/>
              <Text fontSize={['xl','4xl','6xl','6xl']}>Hello!!</Text>
              <Text fontSize={['lg','3xl','4xl','4xl']} textAlign='center'>
                I'm Carlos Quintero González, Mexican Systems Engineer and this is my
                Portfolio
              </Text>
              <Text fontSize={['lg','3xl','4xl','4xl']} textAlign='center'>
                Here you gonna find my JS and React Skills,
                this website was created with Next.js and lot of effort!!
              </Text>
        </Flex>
      </Box>
    </Box>
  );
}
