import Head from 'next/head';
import { useThemeSwitch } from "../lib/context";
import style from '../styles/WeatherApp.module.css';

export default function weatherApp() {
    const { darkMode } = useThemeSwitch();
    return (
        <div className={darkMode ? style.wrapper_dark : style.wrapper_light}>
            <Head>
                <title>Weather App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={darkMode ? style.main_dark : style.main_light}>
                Weather App
            </main>
        </div>
    );
}